apiVersion: v1
kind: Service
metadata:
  name: commits-to
  labels:
    app.kubernetes.io/instance: commits-to
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: commits-to
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: commits-to
    app.kubernetes.io/name: commits-to
    app.kubernetes.io/part-of: commits-to
    app.kubernetes.io/version: v1
  name: commits-to
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/ignore: "false"
    fluxcd.io/tag.commits-to: regex:^master-[a-f0-9]{7}$
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commits-to
  template:
    metadata:
      annotations:
        config.linkerd.io/trace-collector: oc-collector.tracing:55678
      labels:
        app: commits-to
    spec:
      containers:
      - command: ["npm"]
        args: ["start"]
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:5000/api/v1/user/promises?username=kb
          initialDelaySeconds: 1
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:5000/api/v1/user/promises?username=kb
          initialDelaySeconds: 1
          timeoutSeconds: 5
        env:
        - name: NODE_ENV
          value: development
        - name: APP_PORT
          value: '5000'
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: commits-to-secret
              key: DATABASE_URL
        - name: ENV_NAME
          valueFrom:
            secretKeyRef:
              name: commits-to-secret
              key: ENV_NAME
        - name: PAPERTRAIL_HOST
          valueFrom:
            secretKeyRef:
              name: commits-to-secret
              key: PAPERTRAIL_HOST
        - name: PAPERTRAIL_PORT
          valueFrom:
            secretKeyRef:
              name: commits-to-secret
              key: PAPERTRAIL_PORT
        - name: MAILGUN_DOMAIN
          valueFrom:
            secretKeyRef:
              name: commits-to-secret
              key: MAILGUN_DOMAIN
        - name: MAILGUN_FROM
          valueFrom:
            secretKeyRef:
              name: commits-to-secret
              key: MAILGUN_FROM
        - name: MAILGUN_KEY
          valueFrom:
            secretKeyRef:
              name: commits-to-secret
              key: MAILGUN_KEY
        imagePullPolicy: IfNotPresent
        image: quay.io/kingdonb/commitsto:master-74e605d
        name: commits-to
        ports:
        - containerPort: 5000
          name: http
        resources:
          limits:
            cpu: 250m
