apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crdflux.crdtest.example.com
spec:
  group: crdtest.example.com
  versions:
  - name: v1
    served: true
    storage: true
  version: v1
  scope: Namespaced
  names:
    plural: crdfluxes
    singular: crdflux
    kind: CrdFlux
    shortNames:
    - t
