apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/local-path-provisioner
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
